### ISSUE TITLE
求邀请

### ISSUE THREAD

**Issue by chengxiaoxu** [asdf2014/gitment#98]
I Have You

**Comment by asdf2014** [comment]
@chengxiaoxu 欢迎欢迎！已邀请，请点击 https://github.com/asdf2014/algorithm/invitations 链接确认。

确认之后，可以使用下面这个命令，一键提交第一个 commit

```bash
bash -c "$(curl -L https://raw.githubusercontent.com/asdf2014/algorithm/master/first_commit.sh)"
